C:\Program Files (x86)\Arduino\arduino-builder -dump-prefs -logger=machine -hardware "C:\Program Files (x86)\Arduino\hardware" -tools "C:\Program Files (x86)\Arduino\tools-builder" -tools "C:\Program Files (x86)\Arduino\hardware\tools\avr" -built-in-libraries "C:\Program Files (x86)\Arduino\libraries" -libraries "C:\Users\Dave\Documents\Arduino\libraries" -fqbn=arduino:avr:uno -ide-version=10609 -build-path "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp" -warnings=all -prefs=build.warn_data_percentage=75 -verbose "C:\Program Files (x86)\Arduino\examples\01.Basics\Blink\Blink.ino"

C:\Program Files (x86)\Arduino\arduino-builder -compile -logger=machine -hardware "C:\Program Files (x86)\Arduino\hardware" -tools "C:\Program Files (x86)\Arduino\tools-builder" -tools "C:\Program Files (x86)\Arduino\hardware\tools\avr" -built-in-libraries "C:\Program Files (x86)\Arduino\libraries" -libraries "C:\Users\Dave\Documents\Arduino\libraries" -fqbn=arduino:avr:uno -ide-version=10609 -build-path "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp" -warnings=all -prefs=build.warn_data_percentage=75 -verbose "C:\Program Files (x86)\Arduino\examples\01.Basics\Blink\Blink.ino"

"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10609 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\sketch\Blink.ino.cpp" -o "nul"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10609 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\sketch\Blink.ino.cpp" -o "nul"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10609 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\sketch\Blink.ino.cpp" -o "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\preproc\ctags_target_for_gcc_minus_e.cpp"
"C:\Program Files (x86)\Arduino\tools-builder\ctags\5.8-arduino10/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\preproc\ctags_target_for_gcc_minus_e.cpp"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10609 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\sketch\Blink.ino.cpp" -o "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\sketch\Blink.ino.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-gcc" -c -g -x assembler-with-cpp -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10609 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\wiring_pulse.S" -o "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\wiring_pulse.S.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-gcc" -c -g -Os -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10609 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\WInterrupts.c" -o "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\WInterrupts.c.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-gcc" -c -g -Os -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10609 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\hooks.c" -o "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\hooks.c.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-gcc" -c -g -Os -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10609 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\wiring.c" -o "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\wiring.c.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-gcc" -c -g -Os -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10609 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\wiring_analog.c" -o "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\wiring_analog.c.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-gcc" -c -g -Os -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10609 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\wiring_digital.c" -o "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\wiring_digital.c.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-gcc" -c -g -Os -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10609 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\wiring_pulse.c" -o "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\wiring_pulse.c.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-gcc" -c -g -Os -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10609 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\wiring_shift.c" -o "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\wiring_shift.c.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10609 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\CDC.cpp" -o "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\CDC.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10609 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\HardwareSerial.cpp" -o "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\HardwareSerial.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10609 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\HardwareSerial0.cpp" -o "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\HardwareSerial0.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10609 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\HardwareSerial1.cpp" -o "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\HardwareSerial1.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10609 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\HardwareSerial2.cpp" -o "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\HardwareSerial2.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10609 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\HardwareSerial3.cpp" -o "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\HardwareSerial3.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10609 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\IPAddress.cpp" -o "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\IPAddress.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10609 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\PluggableUSB.cpp" -o "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\PluggableUSB.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10609 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\Print.cpp" -o "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\Print.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10609 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\Stream.cpp" -o "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\Stream.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10609 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\Tone.cpp" -o "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\Tone.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10609 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\USBCore.cpp" -o "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\USBCore.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10609 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\WMath.cpp" -o "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\WMath.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10609 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\WString.cpp" -o "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\WString.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10609 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\abi.cpp" -o "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\abi.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10609 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\main.cpp" -o "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\main.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10609 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\new.cpp" -o "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\new.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\core.a" "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\wiring_pulse.S.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\core.a" "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\WInterrupts.c.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\core.a" "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\hooks.c.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\core.a" "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\wiring.c.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\core.a" "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\wiring_analog.c.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\core.a" "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\wiring_digital.c.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\core.a" "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\wiring_pulse.c.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\core.a" "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\wiring_shift.c.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\core.a" "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\CDC.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\core.a" "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\HardwareSerial.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\core.a" "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\HardwareSerial0.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\core.a" "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\HardwareSerial1.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\core.a" "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\HardwareSerial2.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\core.a" "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\HardwareSerial3.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\core.a" "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\IPAddress.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\core.a" "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\PluggableUSB.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\core.a" "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\Print.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\core.a" "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\Stream.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\core.a" "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\Tone.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\core.a" "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\USBCore.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\core.a" "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\WMath.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\core.a" "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\WString.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\core.a" "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\abi.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\core.a" "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\main.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\core.a" "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\core\new.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-gcc" -Wall -Wextra -Os -Wl,--gc-sections -mmcu=atmega328p  -o "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp/Blink.ino.elf" "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp\sketch\Blink.ino.cpp.o" "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp/core\core.a" "-LC:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp" -lm
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-objcopy" -O ihex -j .eeprom --set-section-flags=.eeprom=alloc,load --no-change-warnings --change-section-lma .eeprom=0  "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp/Blink.ino.elf" "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp/Blink.ino.eep"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-objcopy" -O ihex -R .eeprom  "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp/Blink.ino.elf" "C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp/Blink.ino.hex"

Sketch uses 1,066 bytes (3%) of program storage space. Maximum is 32,256 bytes.
Global variables use 9 bytes (0%) of dynamic memory, leaving 2,039 bytes for local variables. Maximum is 2,048 bytes.
C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avrdude -CC:\Program Files (x86)\Arduino\hardware\tools\avr/etc/avrdude.conf -v -patmega328p -carduino -PCOM3 -b115200 -D -Uflash:w:C:\Users\Dave\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp/Blink.ino.hex:i 

avrdude: Version 6.0.1, compiled on Apr 15 2015 at 19:59:58
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2009 Joerg Wunsch

         System wide configuration file is "C:\Program Files (x86)\Arduino\hardware\tools\avr/etc/avrdude.conf"

         Using Port                    : COM3
         Using Programmer              : arduino
         Overriding Baud Rate          : 115200
avrdude: ser_open(): can't open device "\\.\COM3": The system cannot find the file specified.



avrdude done.  Thank you.



########################## MY VERSION 

"C:\Program Files (x86)\Arduino\arduino-builder" -logger=human -hardware "C:\Program Files (x86)\Arduino\hardware" -tools "C:\Program Files (x86)\Arduino\tools-builder" -tools "C:\Program Files (x86)\Arduino\hardware\tools\avr" -built-in-libraries "C:\Program Files (x86)\Arduino\libraries" -libraries "C:\Users\Dave Gordon\Documents\Arduino\libraries" -fqbn=arduino:avr:uno -ide-version=10609 -build-path "C:\Users\Dave Gordon\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp" -warnings=all -prefs=build.warn_data_percentage=75 -verbose "C:\Program Files (x86)\Arduino\examples\01.Basics\Blink\Blink.ino"

"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avrdude" -C "C:\Program Files (x86)\Arduino\hardware\tools\avr/etc/avrdude.conf" -v -patmega328p -carduino -PCOM5 -b115200 -D -Uflash:w:"C:\Users\Dave Gordon\AppData\Local\Temp\build9c9ef3bdfe2fccb480bc6e4bac749e41.tmp/Blink.ino.hex":i